export default [
  {
    title: "iPhone 13 Pro Max",
    value: "iPhone 13 Pro Max",
    color: [
      { title: "Gold", value: "Gold" },
      { title: "Graphit", value: "Graphit" },
      { title: "Sierrablau", value: "Sierrablau" },
      { title: "Silber", value: "Silber" },
    ],
    memory: [
      { title: "1 TB", value: "1 TB" },
      { title: "512 GB", value: "512 GB" },
      { title: "256 GB", value: "256 GB" },
      { title: "128 GB", value: "128 GB" },
    ],
    imageUrl: "/assets/iphone_13_pro_max.jpeg",
  },
  {
    title: "iPhone 13 Pro",
    value: "iPhone 13 Pro",
    color: [
      { title: "Gold", value: "Gold" },
      { title: "Graphit", value: "Graphit" },
      { title: "Sierrablau", value: "Sierrablau" },
      { title: "Silber", value: "Silber" },
    ],
    memory: [
      { title: "1 TB", value: "1 TB" },
      { title: "512 GB", value: "512 GB" },
      { title: "256 GB", value: "256 GB" },
      { title: "128 GB", value: "128 GB" },
    ],
    imageUrl: "/assets/iphone_13__pro.jpg",
  },
  {
    title: "iPhone 13",
    value: "iPhone 13",
    color: [
      { title: "(PRODUCT)RED", value: "(PRODUCT)RED" },
      { title: "Blau", value: "Blau" },
      { title: "Mitternacht", value: "Mitternacht" },
      { title: "Polarstern", value: "Polarstern" },
      { title: "Rosé", value: "Rosé" },
    ],
    memory: [
      { title: "512 GB", value: "512 GB" },
      { title: "256 GB", value: "256 GB" },
      { title: "128 GB", value: "128 GB" },
    ],
    imageUrl: "/assets/iphone_13.jpg",
  },
  {
    title: "iPhone 13 mini",
    value: "iPhone 13 mini",
    color: [
      { title: "(PRODUCT)RED", value: "(PRODUCT)RED" },
      { title: "Blau", value: "Blau" },
      { title: "Mitternacht", value: "Mitternacht" },
      { title: "Polarstern", value: "Polarstern" },
      { title: "Rosé", value: "Rosé" },
    ],
    memory: [
      { title: "512 GB", value: "512 GB" },
      { title: "256 GB", value: "256 GB" },
      { title: "128 GB", value: "128 GB" },
    ],
    imageUrl: "/assets/iphone-13-mini.jpeg",
  },
  {
    title: "iPhone 12 Pro Max",
    value: "iPhone 12 Pro Max",
    color: [
      { title: "Gold", value: "Gold" },
      { title: "Graphit", value: "Graphit" },
      { title: "Pazifikblau", value: "Pazifikblau" },
      { title: "Silber", value: "Silber" },
    ],
    memory: [
      { title: "512 GB", value: "512 GB" },
      { title: "256 GB", value: "256 GB" },
      { title: "128 GB", value: "128 GB" },
    ],
    imageUrl: "/assets/iphone12_pro_max.jpeg",
  },
  {
    title: "iPhone 12 Pro",
    value: "iPhone 12 Pro",
    color: [
      { title: "Gold", value: "Gold" },
      { title: "Graphit", value: "Graphit" },
      { title: "Pazifikblau", value: "Pazifikblau" },
      { title: "Silber", value: "Silber" },
    ],
    memory: [
      { title: "512 GB", value: "512 GB" },
      { title: "256 GB", value: "256 GB" },
      { title: "128 GB", value: "128 GB" },
    ],
    imageUrl: "/assets/iphone__12_pro.png",
  },
  {
    title: "iPhone 12",
    value: "iPhone 12",
    color: [
      { title: "(PRODUCT)RED", value: "(PRODUCT)RED" },
      { title: "Blau", value: "Blau" },
      { title: "Grün", value: "Grün" },
      { title: "Schwarz", value: "Schwarz" },
      { title: "Violett", value: "Violett" },
      { title: "Weiß", value: "Weiß" },
    ],
    memory: [
      { title: "256 GB", value: "256 GB" },
      { title: "128 GB", value: "128 GB" },
      { title: "64 GB", value: "64 GB" },
    ],
    imageUrl: "/assets/iphone__12.jpeg",
  },
  {
    title: "iPhone 12 mini",
    value: "iPhone 12 mini",
    color: [
      { title: "(PRODUCT)RED", value: "(PRODUCT)RED" },
      { title: "Blau", value: "Blau" },
      { title: "Grün", value: "Grün" },
      { title: "Schwarz", value: "Schwarz" },
      { title: "Violett", value: "Violett" },
      { title: "Weiß", value: "Weiß" },
    ],
    memory: [
      { title: "256 GB", value: "256 GB" },
      { title: "128 GB", value: "128 GB" },
      { title: "64 GB", value: "64 GB" },
    ],
    imageUrl: "/assets/iphone_12_mini.jpeg",
  },
  {
    title: "iPhone SE (2. Generation)",
    value: "iPhone SE (2. Generation)",
    color: [
      { title: "(PRODUCT)RED", value: "(PRODUCT)RED" },
      { title: "Schwarz", value: "Schwarz" },
      { title: "Weiß", value: "Weiß" },
    ],
    memory: [
      { title: "256 GB", value: "256 GB" },
      { title: "128 GB", value: "128 GB" },
      { title: "64 GB", value: "64 GB" },
    ],
    imageUrl: "/assets/apple_iphone_se_2.jpg",
  },
  {
    title: "iPhone 11 Pro Max",
    value: "iPhone 11 Pro Max",
    color: [
      { title: "Gold", value: "Gold" },
      { title: "Nachtgrün", value: "Nachtgrün" },
      { title: "Silber", value: "Silber" },
      { title: "Space Grau", value: "Space Grau" },
    ],
    memory: [
      { title: "512 GB", value: "512 GB" },
      { title: "256 GB", value: "256 GB" },
      { title: "64 GB", value: "64 GB" },
    ],
    imageUrl: "/assets/iphone11pro_max.png",
  },
  {
    title: "iPhone 11 Pro",
    value: "iPhone 11 Pro",
    color: [
      { title: "Gold", value: "Gold" },
      { title: "Nachtgrün", value: "Nachtgrün" },
      { title: "Silber", value: "Silber" },
      { title: "Space Grau", value: "Space Grau" },
    ],
    memory: [
      { title: "512 GB", value: "512 GB" },
      { title: "256 GB", value: "256 GB" },
      { title: "64 GB", value: "64 GB" },
    ],
    imageUrl: "/assets/iPhone_11_Pro.jpg",
  },
  {
    title: "iPhone 11",
    value: "iPhone 11",
    color: [
      { title: "(PRODUCT)RED", value: "(PRODUCT)RED" },
      { title: "Gelb", value: "Gelb" },
      { title: "Grün", value: "Grün" },
      { title: "Schwarz", value: "Schwarz" },
      { title: "Violett", value: "Violett" },
      { title: "Weiß", value: "Weiß" },
    ],
    memory: [
      { title: "256 GB", value: "256 GB" },
      { title: "128 GB", value: "128 GB" },
      { title: "64 GB", value: "64 GB" },
    ],
    imageUrl: "/assets/iphone11.jpeg",
  },
  {
    title: "iPhone XR",
    value: "iPhone XR",
    color: [
      { title: "(PRODUCT)RED", value: "(PRODUCT)RED" },
      { title: "Blau", value: "Blau" },
      { title: "Gelb", value: "Gelb" },
      { title: "Koralle", value: "Koralle" },
      { title: "Schwarz", value: "Schwarz" },
      { title: "Weiß", value: "Weiß" },
    ],
    memory: [
      { title: "256 GB", value: "256 GB" },
      { title: "128 GB", value: "128 GB" },
      { title: "64 GB", value: "64 GB" },
    ],
    imageUrl: "/assets/iphone_XR.jpg",
  },
  {
    title: "iPhone XS",
    value: "iPhone XS",
    color: [
      { title: "Gold", value: "Gold" },
      { title: "Silber", value: "Silber" },
      { title: "Space Grau", value: "Space Grau" },
    ],
    memory: [
      { title: "512 GB", value: "512 GB" },
      { title: "256 GB", value: "256 GB" },
      { title: "64 GB", value: "64 GB" },
    ],
    imageUrl: "/assets/iphone_XS.png",
  },
  {
    title: "iPhone XS Max",
    value: "iPhone XS Max",
    color: [
      { title: "Gold", value: "Gold" },
      { title: "Silber", value: "Silber" },
      { title: "Space Grau", value: "Space Grau" },
    ],
    memory: [
      { title: "512 GB", value: "512 GB" },
      { title: "256 GB", value: "256 GB" },
      { title: "64 GB", value: "64 GB" },
    ],
    imageUrl: "/assets/iphone_xs_max.jpg",
  },
  {
    title: "iPhone XS",
    value: "iPhone XS",
    color: [
      { title: "Gold", value: "Gold" },
      { title: "Silber", value: "Silber" },
      { title: "Space Grau", value: "Space Grau" },
    ],
    memory: [
      { title: "512 GB", value: "512 GB" },
      { title: "256 GB", value: "256 GB" },
      { title: "64 GB", value: "64 GB" },
    ],
    imageUrl: "",
  },
  {
    title: "iPhone X",
    value: "iPhone X",
    color: [
      { title: "Silber", value: "Silber" },
      { title: "Space Grau", value: "Space Grau" },
    ],
    memory: [
      { title: "256 GB", value: "256 GB" },
      { title: "64 GB", value: "64 GB" },
    ],
    imageUrl: "/assets/iphone_X.jpg",
  },
  {
    title: "iPhone 8",
    value: "iPhone 8",
    color: [
      { title: "Gold", value: "Gold" },
      { title: "Rot", value: "Rot" },
      { title: "Silber", value: "Silber" },
      { title: "Space Grau", value: "Space Grau" },
    ],
    memory: [
      { title: "256 GB", value: "256 GB" },
      { title: "128 GB", value: "128 GB" },
      { title: "64 GB", value: "64 GB" },
    ],
    imageUrl: "/assets/iphone8.jpg",
  },
  {
    title: "iPhone 8 Plus",
    value: "iPhone 8 Plus",
    color: [
      { title: "Gold", value: "Gold" },
      { title: "Rot", value: "Rot" },
      { title: "Silber", value: "Silber" },
      { title: "Space Grau", value: "Space Grau" },
    ],
    memory: [
      { title: "256 GB", value: "256 GB" },
      { title: "128 GB", value: "128 GB" },
      { title: "64 GB", value: "64 GB" },
    ],
    imageUrl: "/assets/iphone8_plus.png",
  },
  {
    title: "iPhone 7",
    value: "iPhone 7",
    color: [
      { title: "Diamantschwarz", value: "Diamantschwarz" },
      { title: "Gold", value: "Gold" },
      { title: "Roségold", value: "Roségold" },
      { title: "Rot", value: "Rot" },
      { title: "Schwarz", value: "Schwarz" },
      { title: "Silber", value: "Silber" },
    ],
    memory: [
      { title: "256 GB", value: "256 GB" },
      { title: "128 GB", value: "128 GB" },
      { title: "32 GB", value: "32 GB" },
    ],
    imageUrl: "/assets/iphone7.jpeg",
  },
  {
    title: "iPhone 7 Plus",
    value: "iPhone 7 Plus",
    color: [
      { title: "Diamantschwarz", value: "Diamantschwarz" },
      { title: "Gold", value: "Gold" },
      { title: "Roségold", value: "Roségold" },
      { title: "Rot", value: "Rot" },
      { title: "Schwarz", value: "Schwarz" },
      { title: "Silber", value: "Silber" },
    ],
    memory: [
      { title: "256 GB", value: "256 GB" },
      { title: "128 GB", value: "128 GB" },
      { title: "32 GB", value: "32 GB" },
    ],
    imageUrl: "/assets/iphone7_plus.jpeg",
  },
  {
    title: "iPhone 6s",
    value: "iPhone 6s",
    color: [
      { title: "Gold", value: "Gold" },
      { title: "Roségold", value: "Roségold" },
      { title: "Silber", value: "Silber" },
      { title: "Space Grau", value: "Space Grau" },
    ],
    memory: [
      { title: "128 GB", value: "128 GB" },
      { title: "64 GB", value: "64 GB" },
      { title: "32 GB", value: "32 GB" },
      { title: "16 GB", value: "16 GB" },
    ],
    imageUrl: "/assets/iphone6s.jpg",
  },
  {
    title: "iPhone 6s Plus",
    value: "iPhone 6s Plus",
    color: [
      { title: "Gold", value: "Gold" },
      { title: "Roségold", value: "Roségold" },
      { title: "Silber", value: "Silber" },
      { title: "Space Grau", value: "Space Grau" },
    ],
    memory: [
      { title: "128 GB", value: "128 GB" },
      { title: "64 GB", value: "64 GB" },
      { title: "32 GB", value: "32 GB" },
      { title: "16 GB", value: "16 GB" },
    ],
    imageUrl: "/assets/iphone_6s_plus.jpg",
  },
  {
    title: "iPhone 6",
    value: "iPhone 6",
    color: [
      { title: "Gold", value: "Gold" },
      { title: "Silber", value: "Silber" },
      { title: "Space Grau", value: "Space Grau" },
    ],
    memory: [
      { title: "128 GB", value: "128 GB" },
      { title: "64 GB", value: "64 GB" },
      { title: "32 GB", value: "32 GB" },
      { title: "16 GB", value: "16 GB" },
    ],
    imageUrl: "/assets/iphone6.jpg",
  },
  {
    title: "iPhone SE",
    value: "iPhone SE",
    color: [
      { title: "Gold", value: "Gold" },
      { title: "Roségold", value: "Roségold" },
      { title: "Silber", value: "Silber" },
      { title: "Space Grau", value: "Space Grau" },
    ],
    memory: [
      { title: "128 GB", value: "128 GB" },
      { title: "64 GB", value: "64 GB" },
      { title: "32 GB", value: "32 GB" },
      { title: "16 GB", value: "16 GB" },
    ],
    imageUrl: "/assets/iphone_SE.jpg",
  },
];
